---
- name: Create system user for Node Exporter
  user:
    name: node_exporter
    system: yes
    shell: /bin/false
    create_home: no

- name: Download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-arm64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"

- name: Extract Node Exporter
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/tmp/"
    remote_src: yes
    creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-arm64/node_exporter"

- name: Install Node Exporter binary
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-arm64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: "0755"
    remote_src: yes

- name: Create Node Exporter systemd service
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      User=node_exporter
      ExecStart=/usr/local/bin/node_exporter --web.listen-address=:{{ node_exporter_port }}
      Restart=always

      [Install]
      WantedBy=multi-user.target
  notify: restart_node_exporter

- name: Start and enable Node Exporter
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes
