---
- name: Create system user for Prometheus
  user:
    name: prometheus
    system: yes
    shell: /bin/false
    create_home: no

- name: Create Prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-arm64.tar.gz"
    dest: "/tmp/prometheus.tar.gz"

- name: Extract Prometheus
  unarchive:
    src: "/tmp/prometheus.tar.gz"
    dest: "/tmp/"
    remote_src: yes
    creates: "/tmp/prometheus-{{ prometheus_version }}.linux-arm64/prometheus"

- name: Install Prometheus binary
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-arm64/prometheus"
    dest: "/usr/local/bin/prometheus"
    mode: "0755"
    remote_src: yes

- name: Deploy Prometheus config
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
  notify: restart_prometheus

- name: Create Prometheus systemd service
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      After=network.target

      [Service]
      User=prometheus
      ExecStart=/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus/
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Start and enable Prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes
