---
- name: restart_grafana
  systemd:
    name: grafana
    state: restarted
    daemon_reload: yes---
- name: restart_grafana
  systemd:
    name: grafana
    state: restarted
    daemon_reload: yes
